// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BussinessObject;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace DataAccsess;

public partial class DBLibraryManagementContext : DbContext
{
    public DBLibraryManagementContext()

    {

    }
    public DBLibraryManagementContext(DbContextOptions<DBLibraryManagementContext> options)
        : base(options)
    {
    }


    // Đọc connection string từ appsettings.json

    private static string ReadConnectionString()

    {

        var cfg = new ConfigurationBuilder()

            .SetBasePath(AppContext.BaseDirectory)

            .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)

            .Build();



        return cfg.GetConnectionString("DBLibraryManagement");

    }



    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)

    {

        if (!optionsBuilder.IsConfigured)

        {

            var conn = ReadConnectionString();

            if (string.IsNullOrWhiteSpace(conn))

                throw new InvalidOperationException("Missing connection string 'DBLibraryManagement' in appsettings.json.");



            optionsBuilder.UseSqlServer(conn);

        }

    }

    public virtual DbSet<Author> Authors { get; set; }

    public virtual DbSet<Book> Books { get; set; }

    public virtual DbSet<BookInstance> BookInstances { get; set; }

    public virtual DbSet<Borrow> Borrows { get; set; }

    public virtual DbSet<BorrowDetail> BorrowDetails { get; set; }

    public virtual DbSet<BorrowFine> BorrowFines { get; set; }

    public virtual DbSet<Librarian> Librarians { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Author>(entity =>
        {
            entity.HasKey(e => e.AuthorId).HasName("PK__Author__70DAFC149884B621");

            entity.ToTable("Author");

            entity.Property(e => e.AuthorId).HasColumnName("AuthorID");
            entity.Property(e => e.Country).HasMaxLength(100);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(150);
        });

        modelBuilder.Entity<Book>(entity =>
        {
            entity.HasKey(e => e.BookId).HasName("PK__Book__3DE0C2273D474FDC");

            entity.ToTable("Book");

            entity.Property(e => e.BookId).HasColumnName("BookID");
            entity.Property(e => e.AuthorId).HasColumnName("AuthorID");
            entity.Property(e => e.Category).HasMaxLength(255);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.Author).WithMany(p => p.Books)
                .HasForeignKey(d => d.AuthorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Book_Author");
        });

        modelBuilder.Entity<BookInstance>(entity =>
        {
            entity.HasKey(e => e.InstanceId).HasName("PK__BookInst__5C51996F49A6CCA6");

            entity.ToTable("BookInstance");

            entity.Property(e => e.InstanceId).HasColumnName("InstanceID");
            entity.Property(e => e.BookId).HasColumnName("BookID");
            entity.Property(e => e.Condition).HasMaxLength(20);

            entity.HasOne(d => d.Book).WithMany(p => p.BookInstances)
                .HasForeignKey(d => d.BookId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookInstance_Book");
        });

        modelBuilder.Entity<Borrow>(entity =>
        {
            entity.HasKey(e => e.BorrowId).HasName("PK__Borrow__4295F85F65A29E50");

            entity.ToTable("Borrow");

            entity.Property(e => e.BorrowId).HasColumnName("BorrowID");
            entity.Property(e => e.BorrowDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.LibrarianId).HasColumnName("LibrarianID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.StudentId).HasColumnName("StudentID");

            entity.HasOne(d => d.Librarian).WithMany(p => p.Borrows)
                .HasForeignKey(d => d.LibrarianId)
                .HasConstraintName("FK_Borrow_Librarian");

            entity.HasOne(d => d.Student).WithMany(p => p.Borrows)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Borrow_Student");
        });

        modelBuilder.Entity<BorrowDetail>(entity =>
        {
            entity.HasKey(e => e.BorrowDetailId).HasName("PK__BorrowDe__2D6701668916DE41");

            entity.ToTable("BorrowDetail");

            entity.Property(e => e.BorrowDetailId).HasColumnName("BorrowDetailID");
            entity.Property(e => e.BorrowId).HasColumnName("BorrowID");
            entity.Property(e => e.InstanceId).HasColumnName("InstanceID");

            entity.HasOne(d => d.Borrow).WithMany(p => p.BorrowDetails)
                .HasForeignKey(d => d.BorrowId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BorrowDetail_Borrow");

            entity.HasOne(d => d.Instance).WithMany(p => p.BorrowDetails)
                .HasForeignKey(d => d.InstanceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BorrowDetail_BookInstance");
        });

        modelBuilder.Entity<BorrowFine>(entity =>
        {
            entity.HasKey(e => e.FineId).HasName("PK__BorrowFi__9D4A9BCCB278E57E");

            entity.ToTable("BorrowFine");

            entity.Property(e => e.FineId).HasColumnName("FineID");
            entity.Property(e => e.BorrowDetailId).HasColumnName("BorrowDetailID");
            entity.Property(e => e.Reason).HasMaxLength(255);

            entity.HasOne(d => d.BorrowDetail).WithMany(p => p.BorrowFines)
                .HasForeignKey(d => d.BorrowDetailId)
                .HasConstraintName("FK_BorrowFine_BorrowDetail");
        });

        modelBuilder.Entity<Librarian>(entity =>
        {
            entity.HasKey(e => e.LibrarianId).HasName("PK__Libraria__E4D86D9D00A94490");

            entity.ToTable("Librarian");

            entity.Property(e => e.LibrarianId).HasColumnName("LibrarianID");
            entity.Property(e => e.Code)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Name).HasMaxLength(50);
            entity.Property(e => e.Password)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.StudentId).HasName("PK__Student__32C52A79E6086AA4");

            entity.ToTable("Student");

            entity.HasIndex(e => e.Code, "UQ_Student_Code").IsUnique();

            entity.HasIndex(e => e.Email, "UQ_Student_Email").IsUnique();

            entity.Property(e => e.StudentId).HasColumnName("StudentID");
            entity.Property(e => e.Class).HasMaxLength(50);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Email)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.Password)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}