// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BussinessObject;

public partial class Author
{
    public int AuthorId { get; set; }

    public string FullName { get; set; }

    public string Country { get; set; }

    public virtual ICollection<Book> Books { get; set; } = new List<Book>();
}