// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BussinessObject;

public partial class Book
{
    public int BookId { get; set; }

    public string Title { get; set; }

    public int AuthorId { get; set; }

    public int? PublishYear { get; set; }

    public int Quantity { get; set; }

    public decimal? Price { get; set; }

    public string Category { get; set; }

    public virtual Author Author { get; set; }

    public virtual ICollection<BookInstance> BookInstances { get; set; } = new List<BookInstance>();
}