// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BussinessObject;

public partial class BookInstance
{
    public int InstanceId { get; set; }

    public int BookId { get; set; }

    public string Condition { get; set; }

    public virtual Book Book { get; set; }

    public virtual ICollection<BorrowDetail> BorrowDetails { get; set; } = new List<BorrowDetail>();
}