// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BussinessObject;

public partial class BorrowFine
{
    public int FineId { get; set; }

    public int? BorrowDetailId { get; set; }

    public int? Amount { get; set; }

    public string Reason { get; set; }

    public virtual BorrowDetail BorrowDetail { get; set; }
}