// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BussinessObject;

public partial class BorrowDetail
{
    public int BorrowDetailId { get; set; }

    public int BorrowId { get; set; }

    public int InstanceId { get; set; }

    public virtual Borrow Borrow { get; set; }

    public virtual ICollection<BorrowFine> BorrowFines { get; set; } = new List<BorrowFine>();

    public virtual BookInstance Instance { get; set; }
}