// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BussinessObject;

public partial class Borrow
{
    public int BorrowId { get; set; }

    public int StudentId { get; set; }

    public DateOnly BorrowDate { get; set; }

    public DateOnly? ReturnDate { get; set; }

    public int? LibrarianId { get; set; }

    public string Status { get; set; }

    public virtual ICollection<BorrowDetail> BorrowDetails { get; set; } = new List<BorrowDetail>();

    public virtual Librarian Librarian { get; set; }

    public virtual Student Student { get; set; }
}