// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BussinessObject;

public partial class Librarian
{
    public int LibrarianId { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Password { get; set; }

    public virtual ICollection<Borrow> Borrows { get; set; } = new List<Borrow>();
}